# -*- coding: utf-8 -*-
"""prj_AI_agent_Q&A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1an_K06Iwf2LwYNWr6oZkPEnr4dM8VWoY

Q&A Assistant Agent by Shrayajyoti Dey
"""

!pip install --upgrade transformers --quiet

from transformers import pipeline
import re
import datetime
import operator
import time

# Initialize the LLM pipeline using PyTorch
llm = pipeline(
    "text2text-generation",
    model="google/flan-t5-large",
    max_length=128,
    framework="pt"
)

# Sample questions for testing
test_questions = [
    {"input": "What is 23 + 19?", "expected_tool": "TOOL_CALCULATOR"},
    {"input": "Can you tell me the current time?", "expected_tool": "TOOL_TIME"},
    {"input": "What time zone am I in?", "expected_tool": "TOOL_TIMEZONE"},
    {"input": "What is today's date and day?", "expected_tool": "TOOL_DATE"},
    {"input": "Can you debug this python code: for i in range(5) print(i)", "expected_tool": "TOOL_DEBUG"},
    {"input": "Who is the president of the USA?", "expected_tool": "ANSWER"},
    {"input": "Calculate 10 * 5 - 3", "expected_tool": "TOOL_CALCULATOR"},
    {"input": "What is an AI?", "expected_tool": "ANSWER"},
]

# Function to run tests
def run_tests():
    print("\n--- Running automated tests ---")
    for i, q in enumerate(test_questions):
        user_input = q["input"]
        expected = q["expected_tool"]
        print(f"\nTest {i+1}: {user_input}")

        decision = llm(f"""
You are an AI agent with access to tools:
calculator, time checker, timezone checker, date checker, python debugger.

Rules:
1. If the user input contains math, respond exactly: TOOL_CALCULATOR
2. If the user input asks for the current time, respond exactly: TOOL_TIME
3. If the user input asks for time zone, respond exactly: TOOL_TIMEZONE
4. If the user input asks for today's date or day, respond exactly: TOOL_DATE
5. If the user input asks to debug or fix Python code, respond exactly: TOOL_DEBUG
6. For all other questions, respond exactly: ANSWER

Do not explain anything.
Only output one of these:
TOOL_CALCULATOR, TOOL_TIME, TOOL_TIMEZONE, TOOL_DATE, TOOL_DEBUG, ANSWER.

User Input: {user_input}
Agent Decision:
""")[0]["generated_text"].strip()

        print("Expected tool:", expected)
        print("Model decision:", decision)

        # Run the selected tool
        if decision == "TOOL_CALCULATOR":
            result = calculator_tool(user_input)
        elif decision == "TOOL_TIME":
            result = time_tool()
        elif decision == "TOOL_TIMEZONE":
            result = timezone_tool()
        elif decision == "TOOL_DATE":
            result = date_day_tool()
        elif decision == "TOOL_DEBUG":
            result = debug_tool(user_input)
        else:
            result = chat_tool(user_input)

        print("Model response:", result)

    print("\n--- Tests complete ---")

print("Agentic AI (type 'exit' to quit)")
print("To run test cases type 'run_tests'")

# ------------------ TOOLS ------------------

# Safe calculator
ops = {'+': operator.add, '-': operator.sub, '*': operator.mul, '/': operator.truediv}

def calculator_tool(text):
    try:
        numbers = [int(n) for n in re.findall(r"\d+", text)]
        operators = re.findall(r"[\+\-\*/]", text)
        result = numbers[0]
        for i, op in enumerate(operators):
            result = ops[op](result, numbers[i+1])
        return str(result)
    except:
        return "I couldn't calculate that."

def time_tool():
    return datetime.datetime.now().strftime("%H:%M:%S")

def timezone_tool():
    tz_name = time.tzname[0]
    offset_hours = -time.timezone // 3600
    return f"Current time zone: {tz_name} (UTC{offset_hours:+d})"

def date_day_tool():
    today = datetime.datetime.now()
    return today.strftime("Today's date is %Y-%m-%d and today is %A")

def debug_tool(code_text):
    prompt = f"""
You are a Python debugging assistant.
The user gives a simple Python program.
Explain possible errors and how to fix them.
Do NOT run the code.
Keep the explanation simple.

Code:
{code_text}

Debugging advice:
"""
    return llm(prompt)[0]["generated_text"].strip()

def chat_tool(user_input):
    prompt_chat = f"""
You are a helpful AI assistant.
Answer clearly in simple language.
User: {user_input}
Assistant:
"""
    return llm(prompt_chat)[0]["generated_text"].strip()

# ------------------ AGENT ------------------

def decide_and_act(user_input):
    prompt = f"""
You are an AI agent with access to tools:
calculator, time checker, timezone checker, date checker, python debugger.

Rules:
1. If the user input contains math, respond exactly: TOOL_CALCULATOR
2. If the user input asks for the current time, respond exactly: TOOL_TIME
3. If the user input asks for time zone, respond exactly: TOOL_TIMEZONE
4. If the user input asks for today's date or day, respond exactly: TOOL_DATE
5. If the user input asks to debug or fix Python code, respond exactly: TOOL_DEBUG
6. For all other questions, respond exactly: ANSWER

Do not explain anything.
Only output one of these:
TOOL_CALCULATOR, TOOL_TIME, TOOL_TIMEZONE, TOOL_DATE, TOOL_DEBUG, ANSWER.

User Input: {user_input}
Agent Decision:
"""
    decision = llm(prompt)[0]["generated_text"].strip()

    if decision == "TOOL_CALCULATOR":
        return calculator_tool(user_input)
    elif decision == "TOOL_TIME":
        return time_tool()
    elif decision == "TOOL_TIMEZONE":
        return timezone_tool()
    elif decision == "TOOL_DATE":
        return date_day_tool()
    elif decision == "TOOL_DEBUG":
        return debug_tool(user_input)
    else:
        return chat_tool(user_input)

# ------------------ MAIN LOOP ------------------

while True:
    user_input = input("You: ")
    if user_input.lower() == "exit":
        print("Agent: Goodbye!")
        break
    elif user_input.lower() == "run_tests":  # ✅ FIXED HERE
        try:
            run_tests()
        except NameError:
            print("No test cases found! Please define `run_tests()` in a previous cell.")
        continue

    result = decide_and_act(user_input)
    print("Agent:", result)